<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patient Availability Request - Honest Health Care</title>
</head>
<body style="background-color: #f9fafb; font-family: Arial, sans-serif; padding: 20px;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 24px; border-radius: 12px; box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);">

        {{-- Logo --}}
        <div style="text-align: center; margin-bottom: 24px;">
            <img src="{{ url('/assests/img/honestlogo.png') }}" alt="Honest Health Care" style="height: 60px; margin: 0 auto;">
        </div>

        {{-- Header --}}
        <h2 style="font-size: 20px; font-weight: 700; color: #111827; margin-bottom: 12px;">Patient Availability Request</h2>

        <p style="color: #374151; font-size: 15px; margin-bottom: 24px;">
            A new request has been submitted to check the availability of a patient in the Honest Health Care system. Please find the patient details below and use the link provided to review or confirm their status.
        </p>

        {{-- Patient Info --}}
        <div style="font-size: 15px; color: #111827; line-height: 1.6;">
            <p><strong>Name:</strong> {{ $first_name }}</p>
            <p><strong>Email:</strong>{{ $email }}</p>
            <p><strong>Address:</strong> {{ $address }}</p>
        </div>

        {{-- Link --}}
        <div style="margin-top: 20px;">
            <p style="margin-bottom: 6px;"><strong>Proposal Link:</strong></p>
            <a href="{{ url('avalableform/' . $encryptedproposal_number) }}" style="color: #3b82f6; text-decoration: underline;">
                {{ url('avalableform/' . $encryptedproposal_number) }}
            </a>
        </div>

        {{-- Footer --}}
        <p style="margin-top: 30px; font-size: 12px; color: #9ca3af; text-align: center;">
            This request was generated by Honest Health Care's patient intake system.
        </p>
    </div>
</body>
</html>
